### ISSUE TITLE
find

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/circular_buffer_js#15]

**Comment by blackeuler** [comment]
I just want to confirm what it is I think this is: 
`
const cb = new circular_buffer(4)
`
`
cb.find(a); // returns `true` if a is in the buffer returns `false` otherwise
`

**Comment by StoneCypher** [comment]
no.  that's what a good language would do.  this is javascript.

find takes a lambda and matches the first item for which the lambda's result is truthy.  if no such element exist, find returns undefined.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

**Comment by StoneCypher** [comment]
```javascript
const cb = new circular_buffer(4);

cb.push( { first: 'stan', last: 'the man' });
cb.push( { first: 'carla', last: 'carla bobarla, banana fanna fo farla' });
cb.push( { first: 'bob', last: 'dobbs' } );
cb.push( { first: 'we feast', last: 'we end their lives' } );

cb.find( el => el.first === 'bob' );  // { first: 'bob', last: 'dobbs' };
```

**Comment by blackeuler** [comment]
I call dibs, @blackeuler , You can assign me to this issue
