### ISSUE TITLE
More random build weirdness

### ISSUE THREAD

**Issue by drohen** [StoneCypher/circular_buffer_js#31]
- In the pkg json file "module" property references `circular_buffer.esm.min.js` but this file is located under the `dist/` dir, which is correct for the "main" property. This makes my build tool complain. Changing module value to `dist/circular_buffer.esm.min.js` makes it work.
- `circular_buffer.d.ts` references `import { version } from './generated/package_version';` which isn't actually in the published npm release. Is it possible to remove this import/export or somehow reinstate the above file to prevent errors?

That's all.

**Comment by StoneCypher** [comment]
with regard to the first one, fixing

with regard to the second one, i'm not actually sure what the correct fix is.  i ***think*** i copy the generated `.d.ts` in, despite that the value has been rolled into the build.  i'm not, however, super confident of that.

can you tell me how to make a repro case?

anyway i'm gonna try that as a fix and let you tell me how it went
